# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10fb1df417d7f52fcdc308512d38fed3196d96af8595fb5555762b11af9d1391366345ebd412b7a758dbc7b9da58db2f10c4eada97a1210bff6b90cccd58274c

test:
  secret_key_base: aa6115af4f12faadfabd0b5b1c83805ba481254b952b3efca79d8381bff4a7c9714f6df7de6e20c60d85aaa4da54f3a3822f21c78875c9c25c60d5c4970468bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
